# Site settings
title: Results Junkies
email: paul@resultsjunkies.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on venture capital, growing startups and small businesses.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://resultsjunkies.com" # the base hostname & protocol for your site
twitter_username: paulsingh
github_username:  paulsingh

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from